concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
jobs:
  in-docker_test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Build with Gradle
      run: "docker run -i --rm \\\n  -v /var/run/docker.sock:/var/run/docker.sock\
        \ \\\n  -v \"$HOME:$HOME\" \\\n  -v \"$PWD:$PWD\" \\\n  -w \"$PWD\" \\\n \
        \ -e AUTO_APPLY_GIT_HOOKS=false \\\n  openjdk:8-jdk-alpine \\\n  ./gradlew\
        \ --no-daemon --continue --scan testcontainers:test --tests '*GenericContainerRuleTest'\n"
name: CI-Docker-Wormhole
on:
  repository_dispatch:
    types: trigger-ga___ci-docker-wormhole.yml
permissions:
  contents: read
