jobs:
  combine-prs:
    permissions:
      checks: read
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: combine-prs
      name: combine-prs
      uses: github/combine-prs@v5.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
name: Combine PRs
on:
  repository_dispatch:
    types: trigger-ga___combine-prs.yml
