env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/actions/setup-java
    - continue-on-error: true
      name: Clear existing docker image cache
      run: docker image prune -af
    - continue-on-error: true
      name: Setup Gradle Build Action
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Run Gradle Build
      run: ./gradlew build --scan --no-daemon -i -x test
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
        OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
      name: Run Gradle Publish
      run: "./gradlew publish \\\n  -Pversion=\"${{github.event.release.tag_name}}\"\
        \ --scan --no-daemon -i\n"
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
permissions:
  contents: read
