jobs:
  update_release_draft:
    if: github.repository == 'testcontainers/testcontainers-java'
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348
name: Release Drafter
on:
  repository_dispatch:
    types: trigger-ga___release-drafter.yml
permissions:
  contents: read
