jobs:
  build:
    if: github.repository == 'testcontainers/testcontainers-java'
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: main
    - continue-on-error: true
      name: Update testcontainers.version property in gradle.properties
      run: 'sed -i "s/^testcontainers\.version=.*/testcontainers\.version=${GITHUB_REF##*/}/g"
        gradle.properties

        git diff

        '
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e
      with:
        body: 'Update testcontainers version to ${GITHUB_REF##*/}

          '
        branch: update-tc-version
        delete-branch: true
        title: Update testcontainers version to ${GITHUB_REF##*/}
name: Update testcontainers version
on:
  repository_dispatch:
    types: trigger-ga___update-testcontainers-version.yml
permissions:
  contents: read
