jobs:
  update-gradle-wrapper:
    if: github.repository == 'testcontainers/testcontainers-java'
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Update Gradle Wrapper
      uses: gradle-update/update-gradle-wrapper-action@0407394b9d173dfc9cf5695f9f560fef6d61a5fe
      with:
        labels: dependencies
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      uses: gradle/actions/wrapper-validation@v3
name: Update Gradle Wrapper
on:
  repository_dispatch:
    types: trigger-ga___update-gradle-wrapper.yml
permissions:
  contents: read
