jobs:
  build:
    if: github.repository == 'testcontainers/testcontainers-java'
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: main
    - continue-on-error: true
      name: Update latest_version property in mkdocs.yml
      run: 'sed -i "s/latest_version: .*/latest_version: ${GITHUB_REF##*/}/g" mkdocs.yml

        git diff

        '
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e
      with:
        body: 'Update docs version to ${GITHUB_REF##*/}

          skip-checks: true

          '
        branch: update-docs-version
        delete-branch: true
        title: Update docs version to ${GITHUB_REF##*/}
name: Update docs version
on:
  repository_dispatch:
    types: trigger-ga___update-docs-version.yml
permissions:
  contents: read
